name: Update Space Coast Feed

on:
  schedule:
    - cron: '0 5 * * *'   # every day at 05:00 UTC (~1 AM EDT)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Generate RSS feed
        run: python generate_feed.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [[ `git status --porcelain` ]]; then
            # update origin to use the GITHUB_TOKEN for authentication
            git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
            git add spacecoast_feed.xml
            git commit -m "Automated feed update: $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
            git push origin HEAD:main
          else
            echo "No changes to commit"
          fi
