name: Update Space Coast Feed

on:
  schedule:
    - cron: '0 5 * * *'   # every day at 05:00 UTC (~1 AM EDT)
  workflow_dispatch:

jobs:
  update-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true  # allows git push with GITHUB_TOKEN

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Generate RSS feed
        run: python generate_feed.py

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add spacecoast_feed.xml
          # commit only if there are changes
          git diff --cached --quiet || git commit -m "Automated feed update: $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
          git push
