name: Update Space Coast Feed

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false  # Use the default GITHUB_TOKEN

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Generate RSS feed
        run: python generate_feed.py

      - name: Check for changes
        id: check_changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add spacecoast_feed.xml
          git diff --cached --quiet || echo "changed=true" >> $GITHUB_ENV

      - name: Commit changes
        if: env.changed == 'true'
        run: |
          git commit -m "Automated feed update: $(date -u +'%Y-%m-%d %H:%M:%S UTC')"

      - name: Push changes
        if: env.changed == 'true'
        run: git push origin main
