name: Update Space Coast Feed

on:
  schedule:
    - cron: '0 5 * * *'   # daily at 05:00 UTC (~1 AM EDT)
  workflow_dispatch:

jobs:
  update-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Generate RSS feed
        run: python generate_feed.py

      - name: Commit & push changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add spacecoast_feed.xml
          # only commit if there are changes
          git diff --cached --quiet || git commit -m "Automated feed update: $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
          # push via token-authenticated URL
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} HEAD:main
